# Generated by Django 5.0.2 on 2024-02-29 01:53

import django.db.models.deletion
import liberty.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=28)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('avatar', models.ImageField(default='avatar.jpg', upload_to=liberty.utils.avatar_path)),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Image.jpg', upload_to=liberty.utils.image_path)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('bid', models.FloatField()),
                ('owner', models.CharField(max_length=28)),
                ('owner_username', models.CharField(max_length=28)),
                ('ends_in', models.TimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='liberty.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='liberty.category')),
            ],
        ),
    ]
